### ISSUE TITLE
Sender.send(msg)---->error

### ISSUE THREAD

**Issue by AlbertChanX** [bluedazzle/wechat_sender#17]
`requests.exceptions.**ConnectionError**: HTTPConnectionPool(host='localhost', port=10245): Max retries exceeded with url: /message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000007352898>: Failed to establish a new connection: [Errno 10061] ',))`

**Comment by iostony** [comment]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10245): Max retries exceeded with url: /message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BB07EBA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
————————
我也是遇到同样的问题，在win10 py3.6 及 ubuntu下一样。不知道怎么解决？

**Comment by hillerliao** [comment]
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10245): Max retries exceeded with url: /message (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BB07EBA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
> ————————
> 我也是遇到同样的问题，在win10 py3.6 及 ubuntu下一样。不知道怎么解决？

解决了吗？

**Comment by hillerliao** [comment]
调用发消息方法的时候，指定port，好像能解决这个问题，但会出现新问题。
